### ISSUE TITLE
PTH model to ONNX

### ISSUE THREAD

**Issue by scottcali** [Chen-KaiTsai/ZeroDCE_JetsonNano#1]
Hi,

    Could you write a script to convert PTH model to ONNX?

    Thanks!

-Scott

**Comment by Chen-KaiTsai** [comment]
I have upload the R11Epoch40_FMD.pt, which include the entire model and weight.

Since I am not familiar with ONNX, I cannot provide a script for you.
Please follow the following two tutorial to export it to onnx with the pt weight file I provided.
1. [Load Entire Model](https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-entire-model)
2. [Export the model to ONNX](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html#export-the-model-to-onnx-format)
